version: '3.8'

services:
  nginx:
    container_name: nginx
    restart: always
    image: gcr.io/${GCP_PROJECT_ID}/${GCE_INSTANCE}-test-nginx:${GITHUB_SHA}
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on: 
      - node
    ports: 
      - 80:80
    
  node:
    container_name: node
    image: gcr.io/${GCP_PROJECT_ID}/${GCE_INSTANCE}-test-node:${GITHUB_SHA}
    # image: ${DOCKER_HUB_USERNAME}/test-git_node:latest
    build:
      dockerfile: Dockerfile
      context: ./node
    volumes:
      - /usr/app/node_modules

  # python:
  #   container_name: python
  #   image: gcr.io/${GCP_PROJECT_ID}/${GCE_INSTANCE}-test-python:latest
  #   build: 
  #     dockerfile: Dockerfile
  #     context: ./python
      