version: '3.8'

services:
  nginx:
    container_name: nginx
    restart: always
    image: f16co/test-git_nginx:latest
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on: 
      - node
    ports: 
      - 80:80
    
  node:
    container_name: node
    image: f16co/test-git_node:latest
    build:
      dockerfile: Dockerfile
      context: ./node
    volumes:
      - /usr/app/node_modules

  # python:
  #   container_name: python
  #   image: gcr.io/${GCP_PROJECT_ID}/${GCE_INSTANCE}-test-python:latest
  #   build: 
  #     dockerfile: Dockerfile
  #     context: ./python
      