version: '3.4'

services:
  node:
    container_name: node
    image: f16co/test-git_node:latest
    build:
      dockerfile: Dockerfile
      context: ./node
    volumes:
      - /usr/app/node_modules

  python:
    container_name: python
    image: f16co/test-git_python:latest
    build: 
      dockerfile: Dockerfile
      context: ./python
      