# name: CD

# on:
#   workflow_run:
#     workflows: [ CI ]
#     branches: [ master ]
#     types:
#       - completed

# jobs:
#   cd:

#     runs-on: ubuntu-latest

#     env: 
#       DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

#     steps:

#     - name: Checkout Repo
#       uses: actions/checkout@v2

#     - name: Login to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#     - name: Docker Compose Build
#       run: |
#         docker-compose build

#     - name: Docker Compose Push
#       run: |
#         docker-compose push

name: CD

on: [push]
# on:
  # workflow_run:
    # workflows: [ CI ]
    # branches: [ master ]
    # types:
    #   - completed

env:
  GCE_INSTANCE: analytics-setting	  
  GCE_INSTANCE_ZONE: asia-northeast3-a

jobs:
  cd: 
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          # workload_identity_provider: projects/${{ secrets.GCP_PROJECT_ID }}/zones/$GCE_INSTANCE_ZONE/instances/$GCE_INSTANCE
          # service_account: $GCE_INSTANCE-account@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
          workload_identity_provider: projects/nota-its/zones/asia-northease3-a/instances/analytics-setting
          service_account: analytics-setting-account@nota-its.iam.gserviceaccount.com

      - name: GCP Github Action
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Use GCP CLI
        run: |-
          gcloud info

      - name: GCP configure docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Connect GCE And execute docker ps
        run: |-
          gcloud compute ssh analytics-setting --zone asia-northeast3-a
      # gcloud compute ssh $GCE_INSTANCE --zone $GCE_INSTANCE_ZONE