name: CD

# on:
#   workflow_run:
#     workflows: [ CI ]
#     branches: [ master ]
#     types:
#       - completed

on: [push]

env:
  GCE_INSTANCE: analytics-setting
  GCE_INSTANCE_ZONE: asia-northeast3-a
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLOUDSDK_PYTHON: /usr/bin/python3
  GITHUB_SHA: ${{ github.sha }}

jobs:
  cd:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: GCP Github Action
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        configure_docker: true

    - name: GCP configure docker
      run: |
        gcloud --quiet auth configure-docker

    - name: Print Python3 Version
      run: |
        python3 --version

    - name: Export Python3 Path
      run: |
        gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
        --command="export CLOUDSDK_PYTHON=/usr/bin/python3"

    - name: Env Python3
      run: |
        gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
        --command="env"

    - name: Docker Compose Build
      run: |
        docker-compose build

    - name: Docker Compose Push
      run: |
        docker-compose push

    - name: Deploy nginx
      run: |
        gcloud compute instances update-container "$GCE_INSTANCE" \
          --zone "$GCE_INSTANCE_ZONE" \
          --container-image "gcr.io/$GCP_PROJECT_ID/$GCE_INSTANCE-test-nginx:latest"

    - name: Deploy node
      run: |
        gcloud compute instances update-container "$GCE_INSTANCE" \
          --zone "$GCE_INSTANCE_ZONE" \
          --container-image "gcr.io/$GCP_PROJECT_ID/$GCE_INSTANCE-test-node:latest"

    # - name: Deploy python
    #   run: |
    #     gcloud compute instances update-container "$GCE_INSTANCE" \
    #       --zone "$GCE_INSTANCE_ZONE" \
    #       --container-image "gcr.io/$GCP_PROJECT_ID/$GCE_INSTANCE-test-python:latest"

    # - name: Make Variable For Docker Nginx Image
    #   run: |
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="docker_image_for_nginx=$(sudo docker images -q f16co/test-git_nginx)"

    # - name: Check Variable For Docker Nginx Image
    #   run: |
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="echo $docker_image_for_nginx"

    # - name: Make Variable For Docker Node Image
    #   run: |
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="docker_image_for_node=$(sudo docker images -q f16co/test-git_node)"

    # - name: Check Variable For Docker Node Image
    #   run: |
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="echo $docker_image_for_node"

    # - name: Make Shell For Docker Stop
    #   run: |
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="echo ' \
    #       if [[ -n $(sudo docker ps -aqf "name=f16co/test-git_nginx") ]]; then \
    #       echo $(sudo docker ps -aqf "name=f16co/test-git_nginx") \
    #       fi \
    #       if [[ -n $(sudo docker ps -aqf "name=f16co/test-git_node") ]]; then \
    #       echo $(sudo docker ps -aqf "name=f16co/test-git_node") \
    #       fi \
    #       if [[ -n $(sudo docker images -q f16co/test-git_nginx) ]]; then \
    #       echo $(sudo docker images -q f16co/test-git_nginx) \
    #       fi \
    #       if [[ -n $(sudo docker images -q f16co/test-git_node) ]]; then \
    #       echo $(sudo docker images -q f16co/test-git_node) \
    #       fi' > analytics-setting.sh"
      # run: |
      #   gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
      #   --command="echo ' \
      #     if [[ -n $(sudo docker ps -aqf "name=f16co/test-git_nginx") && $(sudo docker ps -aqf "name=f16co/test-git_nginx") != " " ]]; then \
      #     sudo docker kill $(sudo docker ps -aqf "name=f16co/test-git_nginx") \
      #     fi \
      #     if [[ -n $(sudo docker ps -aqf "name=f16co/test-git_node") && $(sudo docker ps -aqf "name=f16co/test-git_node") != " " ]]; then \
      #     sudo docker kill $(sudo docker ps -aqf "name=f16co/test-git_node") \
      #     fi \
      #     if [[ -n $(sudo docker images -q f16co/test-git_nginx) && $(sudo docker images -q f16co/test-git_nginx) != " " ]]; then \
      #     sudo docker rmi $(sudo docker images -q f16co/test-git_nginx) \
      #     fi \
      #     if [[ -n $(sudo docker images -q f16co/test-git_node) && $(sudo docker images -q f16co/test-git_node) != " " ]]; then \
      #     sudo docker rmi $(sudo docker images -q f16co/test-git_node) \
      #     fi' > analytics-setting.sh"

    # - name: Check Shell For Docker Stop
    #   run: |
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="cat analytics-setting.sh"
    
    # - name: Run Shell For Docker Stop
    #   run: |
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="sudo sh analytics-setting.sh"

    # - name: Docker Pull Nginx
    #   run: |-
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="sudo docker pull f16co/test-git_nginx:latest"

    # - name: Docker Pull Node
    #   run: |-
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="sudo docker pull f16co/test-git_node:latest"

    # - name: Docker Run Nginx
    #   run: |-
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="sudo docker run f16co/test-git_nginx:latest"

    # - name: Docker Run Node
    #   run: |-
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="sudo docker run f16co/test-git_node:latest"

    # - name: Docker images
    #   run: |-
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="sudo docker images -a"

    # - name: Docker ps
    #   run: |-
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="sudo docker ps -a"

    # - name: Test
    #   run: |
    #     gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" \
    #     --command="echo test"