name: CD for daejeon-600 production

on:
  push:
    tags:
      - daejeon-600_*

env:
  TEST_ENV_1: ${{ vars.TEST_ENV_1 }}

jobs:
  CD_daejeon-600_production:
    name: CD for daejeon-600 production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Set output
        run: echo "TEST_VERSION=$(echo ${GITHUB_REF_NAME} | cut -d_ -f 2)" >> $GITHUB_ENV

      - name: Print env
        run: printenv TEST_VERSION