name: CD for daejeon-600 production

on:
  push:
    tags:
      - daejeon-600_*

env:
  TEST_ENV_1: ${{ vars.TEST_ENV_1 }}

jobs:
  CD_daejeon-600_production:
    name: CD for daejeon-600 production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      
      - name: Get tag annotation
        id: tag-data
        uses: ericcornelissen/git-tag-annotation-action@v2
      
      - name: The output
        run: echo ${{ steps.tag-data.outputs.git-tag-annotation }}

      - name: Get tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.1

      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}