name: CD for daejeon-600 production

on:
  push:
    tags:
      - daejeon-600_*

env:
  TEST_ENV_1: ${{ vars.TEST_ENV_1 }}

jobs:
  CD_daejeon-600_production:
    name: CD for daejeon-600 production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Get GITHUB_REF_NAME
        run: 'echo "$GITHUB_REF_NAME"'

      - name: Get Release Notes
        run: 'echo "$(git tag -l --format="%(contents)" $GITHUB_REF_NAME)" > RELEASE_NOTE'

      - name: Echo Release
        run: 'echo "RELEASE_NOTE: $(cat RELEASE_NOTE)"'

  CD_daejeon-600_dd:
    name: CD for daejeon-600 dd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Echo Release
        run: echo dd

  CD_daejeon-600_release:
    needs: [ CD_daejeon-600_production, CD_daejeon-600_dd ]
    name: CD for daejeon-600 release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Get GITHUB_REF_NAME
        run: 'echo "$GITHUB_REF_NAME"'

      - name: Get Release Notes
        run: 'echo "$(git tag -l --format="%(contents)" $GITHUB_REF_NAME)" > RELEASE_NOTE'

      - name: Echo Release
        run: 'echo "RELEASE_NOTE: $(cat RELEASE_NOTE)"'