name: CD for daejeon-600 production

on:
  push:
    tags:
      - daejeon-600_*

env:
  TEST_ENV_1: ${{ vars.TEST_ENV_1 }}

jobs:
  CD_daejeon-600_production:
    name: CD for daejeon-600 production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - uses: bcomnes/get-git-tag@master
        id: tagName
      
      - name: Get tag annotation
        id: tag-data
        uses: ericcornelissen/git-tag-annotation-action@v2
        with:
          tag: ${{ steps.tagName.outputs.tag }}
      
      - name: The output
        run: echo ${{ steps.tag-data.outputs.git-tag-annotation }}