name: CD for daejeon-600 production

on:
  push:
    tags:
      - daejeon-600_*

env:
  TEST_ENV_1: ${{ vars.TEST_ENV_1 }}

permissions: read-all|write-all

jobs:
  CD_daejeon-600_AWS:
    name: CD for daejeon-600 production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Echo AWS
        run: echo AWS

  CD_daejeon-600_DockerHub:
    name: CD for daejeon-600 dd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Echo DockerHub
        run: echo DockerHub

  CD_daejeon-600_release:
    needs: [ CD_daejeon-600_AWS, CD_daejeon-600_DockerHub ]
    name: CD for daejeon-600 release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: 태그 참조
          draft: false
          prerelease: false