name: CD for daejeon-600 production

on:
  push:
    tags:
      - daejeon-600_*

env:
  TEST_ENV_1: ${{ vars.TEST_ENV_1 }}

jobs:
  CD_daejeon-600_production:
    name: CD for daejeon-600 production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: echo
        run: printenv

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}