name: CD for daejeon-600 production

on:
  push:
    tags:
      - daejeon-600_*

env:
  TEST_ENV_1: ${{ vars.TEST_ENV_1 }}

jobs:
  CD_daejeon-600_production:
    name: CD for daejeon-600 production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: echo
        run: printenv

      - name: Set output
        id: test-version
        run: echo "TEST_VERSION="${GITHUB_REF_NAME} | cut -d_ -f 2"" >> $GITHUB_OUTPUT
        
      - name: Print output
        run: echo ${{ steps.test-version.outputs.TEST_VERSION }}

      - name: Set env
        run: echo "RELEASE_VERSION=${{ steps.test-version.outputs.TEST_VERSION }}" >> $GITHUB_ENV

      - name: Print env
        run: echo ${{ env.RELEASE_VERSION }}