name: CD for daejeon-600 production

on:
  push:
    tags:
      - daejeon-600_*

env:
  TEST_ENV_1: ${{ vars.TEST_ENV_1 }}

permissions:
  id-token: write
  contents: read
  actions: write
  deployments: write

jobs:
  CD_daejeon-600_AWS:
    name: CD for daejeon-600 production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Echo AWS
        run: echo AWS

  CD_daejeon-600_DockerHub:
    name: CD for daejeon-600 dd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Echo DockerHub
        run: echo DockerHub

  CD_daejeon-600_release:
    needs: [ CD_daejeon-600_AWS, CD_daejeon-600_DockerHub ]
    name: CD for daejeon-600 release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Create Release for Tag
        id: release_tag
        uses: Akryum/release-tag@v4.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}